# Background Generator Configuration

[image]
path = "img/sample.jpg"      # Path to the input image
scale_percent = 70           # Scale the image to this percentage of its max allowed size

[output]
path = "None"                # Output file path. "None" for auto naming.
width = 3840                 # Width of output image in pixels
height = 2160                # Height of output image in pixels

[background]
color = "#EFE4D2"     # Background color in hex format. "None" for dominant color.

[noise]
type = "white"         # Options: "perlin", "value", "white", "gaussian", "simplex", "voronoi", "None"
intensity = 0.2      # Noise intensity (0.0-1.0 except for voronoi which should be an integer)
scale = 50           # Noise scale (higher = larger patterns)
seed = 42             # Random seed for reproducible results (optional)

[post]
post=false
effect = "None"     # apply post process: "water", "oil", "painterly", "None"

vignette = true
vig_intensity = 0.1
vig_opacity = 0.1

[border]
width = 5           # Border width in pixels (0 for no border)
color = "#fcba03"   # Border color in hex format
